# Generated by Django 6.0.6 on 2026-07-06 05:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('active_components', models.TextField()),
                ('activation_time_mins', models.IntegerField(help_text='Minutes until drug takes effect')),
                ('clearance_time_hours', models.FloatField(help_text='Hours until drug leaves bloodstream')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_slider', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='tracker.drug')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='tracker.drug')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.reactiondefinition')),
            ],
            options={
                'unique_together': {('drug_a', 'drug_b', 'reaction')},
            },
        ),
    ]
