# Generated by Django 5.0.3 on 2026-07-07 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='drug_a',
            field=models.CharField(help_text='Generic / INN name of first active ingredient (auto-lowercased)', max_length=300),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='drug_b',
            field=models.CharField(help_text='Generic / INN name of second active ingredient (auto-lowercased)', max_length=300),
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-severity_slider', 'drug_a'], 'verbose_name': 'Drug Interaction', 'verbose_name_plural': 'Drug Interactions'},
        ),
        migrations.AlterModelOptions(
            name='reactiondefinition',
            options={'ordering': ['name'], 'verbose_name': 'Reaction Definition', 'verbose_name_plural': 'Reaction Definitions'},
        ),
        migrations.RemoveField(
            model_name='reactiondefinition',
            name='category',
        ),
        migrations.AddField(
            model_name='interaction',
            name='custom_factors',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic pathology constraints: min_age, max_age, gender, conditions'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='remedy',
            field=models.TextField(blank=True, default='', help_text='Clinical remedy instructions returned with warnings'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='tracker.reactiondefinition'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='severity_slider',
            field=models.IntegerField(help_text='Severity index from 1 (minor) to 10 (critical contraindication)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reactiondefinition',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
