# Generated by Django 5.0.3 on 2026-07-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_interaction_drug_a_alter_interaction_drug_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugClassMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=300, unique=True)),
                ('class_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='time_window_hours',
            field=models.IntegerField(default=24, help_text='Clearance / time-to-react window in hours'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='custom_factors',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic pathology constraints: min_age, max_age, min_weight, max_weight, gender'),
        ),
    ]
