# Generated by Django 5.0.3 on 2026-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_drugclassmapping_interaction_time_window_hours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrugClassMapping',
        ),
        migrations.AlterModelOptions(
            name='interaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reactiondefinition',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='interaction',
            name='organ_bitmask',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reactiondefinition',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='custom_factors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='drug_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='drug_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='remedy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='severity_slider',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='time_window_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='reactiondefinition',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('drug_a', 'drug_b')},
        ),
    ]
