# Generated by Django 5.0.3 on 2026-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_drugclassmapping_alter_interaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='drug_a',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='drug_b',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='severity_slider',
            field=models.IntegerField(db_index=True, default=5),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['drug_a'], name='tracker_int_drug_a_fb7a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['drug_b'], name='tracker_int_drug_b_af5aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['drug_a', 'drug_b'], name='tracker_int_drug_a_5d4d8e_idx'),
        ),
    ]
